name: dotNetPrVerificationWorkflow
on:
  workflow_call:
    inputs:
      buildConfiguration:
        description: 'The release stage to deploy to, fx alpha, beta, rc'
        required: true
        type: string
        
jobs:
  build:
    uses: CoreBrew/github-actions-workflows/.github/workflows/dotNet_BuildSolution.yml@main
    with:
      buildConfiguration: {{ inputs.buildConfiguration }}
        
  test:
    needs: build
    uses: CoreBrew/github-actions-workflows/.github/workflows/DotNet_RunTests.yml@main