name: dotNet_RunTests

on:
  workflow_call:
    inputs:    
      runsOn:
        type: string
        required: false
        default: ubuntu-latest  # Default environment if not specified       
        
jobs:
  RunTests:
    runs-on: ${{ inputs.runsOn }}  # Use the input for runs-on

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore
           
      - name: Execute unit tests
        id: testStep # Assign an ID to reference the steps result        
        run: dotnet test






          
