name: dotNet_PrOpenedWorkflow
on:
  workflow_call:
    inputs:
      buildConfiguration:
        description: 'The build configuration to use, fx Debug, Release'        
        required: true
        type: string
        
jobs:
  build:
    uses: CoreBrew/github-actions-workflows/.github/workflows/dotNet_BuildSolution.yml@main
    with:
      buildConfiguration: {{ inputs.buildConfiguration }}
        
  test:
    needs: build
    uses: CoreBrew/github-actions-workflows/.github/workflows/dotNet_RunTests.yml@main