name: dotNet_RunTests

on:
  workflow_call:
    inputs:    
      runsOn:
        type: string
        required: false
        default: ubuntu-latest  # Default environment if not specified       
        
jobs:
  RunTests:
    runs-on: ${{ inputs.runsOn }}  # Use the input for runs-on

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        id: setupDotNet
        with:
          dotnet-version: '10.x'

      - name: Verify .NET version
        run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore
           
      - name: Execute unit tests
        id: testStep # Assign an ID to reference the steps result        
        run: dotnet test






          
