name: dotNet_PackSolution

on:
  workflow_call:
    inputs:
      buildConfiguration:
        description: 'The pack configuration to use, fx Debug, Release'
        required: true
        type: string       
      runsOn:
        type: string
        required: false
        default: ubuntu-latest  # Default environment if not specified           
        
jobs:
  PackSolution:
    runs-on: ${{ inputs.runsOn }}  # Use the input for runs-on
    steps:
      # Ensure the artifacts folder exists
      - name: Create artifacts folder
        run: mkdir artifacts

      - name: Pack the NuGet package 
        run: dotnet pack --configuration ${{ inputs.buildConfiguration}} --output ./artifacts






          
