name: PublishDevNuGetPackage

run-name: Deploy to NuGet.org by @{{ github.actor }}

on:
  workflow_call:
    secrets:
      NuGetApiKey:
        description: 'A NuGetApiKey passed from the caller workflow'
        required: true
        
jobs:
  publish:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    #Commented out since it should be installed already on the github hosted runner
    #- name: Install .NET Core
      #uses: actions/setup-dotnet@v4
      #with:
        #dotnet-version: 8.x.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
            
   #Read the title tag in the .csproj file   
    - name: Read <Title> from .csproj
      shell: pwsh
      run: |
        # Find the .csproj file, use -Recurse to find all csproj files        
        $csprojPath = Get-ChildItem -Path ./Src -Recurse -Filter *.csproj | Select-Object -First 1

        if ($csprojPath) {
            # Use Select-Xml to extract the Title tag value
            $titleNode = Select-Xml -Path $csprojPath.FullName -XPath "//Project/PropertyGroup/Title" | Select-Object -First 1

            if ($titleNode -ne $null) {
                $title = $titleNode.Node.InnerText
                Write-Host "Project Title: $title"
                Add-Content -Path $env:GITHUB_ENV -Value "CSPROJ_TITLE=$title"        
            }
            else {
                Write-Host "No <Title> tag found in the .csproj file."
            }
        }
        else {
            Write-Host "No .csproj file found in the directory."
            Write-Host "Current directory is: $(Get-Location)"
            Write-Host "############# with source #########################"
            Write-Host "Dir command: $(Get-ChildItem -Path ./Src -Recurse)"
            Write-Host "############# without source ######################"        
            Write-Host "Dir command: $(Get-ChildItem -Path . -Recurse)"        
        }
      
      # Use the project title in subsequent steps if needed
    - name: Use Project Title
      run: echo "The project title is $CSPROJ_TITLE"      
      
      # Fetch the latest package version from NuGet.org
    - name: Fetch latest alpha version
      shell: pwsh
      env:
        PACKAGE_ID: $CSPROJ_TITLE  # Replace with the actual package name
      run: |
        $latestVersion = (Invoke-RestMethod -Uri "https://api.nuget.org/v3-flatcontainer/$env:PACKAGE_ID/index.json").versions |
                         Where-Object { $_ -like "*-alpha*" } |
                         Sort-Object { [System.Version]$_ } -Descending |
                         Select-Object -First 1

        if (-not $latestVersion) {
          Write-Host "No alpha version found, starting from 1.0.0-alpha.1"          
          $nextVersion = "1.0.0-alpha.1"
        }
        else {
          Write-Host "Latest alpha version found: $latestVersion"
          $versionParts = $latestVersion -split '-alpha.'
          $majorMinorPatch = $versionParts[0]
          $alphaVersion = [int]$versionParts[1]
          $nextVersion = "$majorMinorPatch-alpha.$($alphaVersion + 1)"
        }
        Write-Host "Latest version is:    $latestVersion"
        Write-Host "Next version will be: $nextVersion"
        echo "::set-output name=nextVersion::$nextVersion"      

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test      

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Debug --no-restore
      
      # Ensure the artifacts folder exists
    - name: Create artifacts folder
      run: mkdir artifacts

    - name: Pack the NuGet package
      run: dotnet pack --configuration Debug --output ./artifacts

      # Find the .nupkg file and push it
    #- name: Push NuGet package
    #  env:
    #    NUGET_API_KEY: ${{ secrets.NuGetApiKey }}
    #  run: |
    #    $nupkg = Get-ChildItem -Path ./artifacts -Filter *.nupkg | Select-Object -First 1
    #    if ($nupkg -eq $null) {
    #      throw "No .nupkg file found in ./artifacts"
    #    }
    #      dotnet nuget push $nupkg.FullName -k $env:NUGET_API_KEY -s https://api.nuget.org/v3/index.json
    #  shell: pwsh
          
